<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class AddGroupeToPermissions extends Migration
{
    public function up()
    {
        // Ajouter la colonne 'groupe' à la table 'permissions'
        Schema::table('permissions', function (Blueprint $table) {
            $table->string('groupe')->nullable();
        });

        // Ajouter les instructions SQL générées
        $sql = "
            
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.store';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.show';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.destroy';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.block';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.unblock';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.VerifiednotBlocknotDelete';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.VerifiedBlocknotDelete';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.updateName';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.updateIcone';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES' WHERE name = 'Managecategory.makeVerified';
UPDATE permissions SET groupe = 'GESTION_ TYPE _LOGEMENT' WHERE name = 'Managehousingtype.store';
UPDATE permissions SET groupe = 'GESTION_ TYPE _LOGEMENT' WHERE name = 'Managehousingtype.show';
UPDATE permissions SET groupe = 'GESTION_ TYPE _LOGEMENT' WHERE name = 'Managehousingtype.updateIcone';
UPDATE permissions SET groupe = 'GESTION_ TYPE _LOGEMENT' WHERE name = 'Managehousingtype.update';
UPDATE permissions SET groupe = 'GESTION_ TYPE _LOGEMENT' WHERE name = 'Managehousingtype.destroy';
UPDATE permissions SET groupe = 'GESTION_ TYPE _LOGEMENT' WHERE name = 'Managehousingtype.destroymultiple';
UPDATE permissions SET groupe = 'GESTION_ TYPE _LOGEMENT' WHERE name = 'Managehousingtype.block';
UPDATE permissions SET groupe = 'GESTION_ TYPE _LOGEMENT' WHERE name = 'Managehousingtype.unblock';
UPDATE permissions SET groupe = 'GESTION_ TYPE _LOGEMENT' WHERE name = 'Managehousingtype.indexBlock';
UPDATE permissions SET groupe = 'GESTION_ CRITERE' WHERE name = 'Managecriteria.store';
UPDATE permissions SET groupe = 'GESTION_ CRITERE' WHERE name = 'Managecriteria.show';
UPDATE permissions SET groupe = 'GESTION_ CRITERE' WHERE name = 'Managecriteria.updateName';
UPDATE permissions SET groupe = 'GESTION_ CRITERE' WHERE name = 'Managecriteria.updateIcone';
UPDATE permissions SET groupe = 'GESTION_ CRITERE' WHERE name = 'Managecriteria.destroy';
UPDATE permissions SET groupe = 'GESTION_ CRITERE' WHERE name = 'Managecriteria.block';
UPDATE permissions SET groupe = 'GESTION_ CRITERE' WHERE name = 'Managecriteria.unblock';
UPDATE permissions SET groupe = 'GESTION_ROLE' WHERE name = 'Managerole.index';
UPDATE permissions SET groupe = 'GESTION_ROLE' WHERE name = 'Managerole.store';
UPDATE permissions SET groupe = 'GESTION_ROLE' WHERE name = 'Managerole.show';
UPDATE permissions SET groupe = 'GESTION_ROLE' WHERE name = 'Managerole.destroy';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.VerifiedBlocknotDelete';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.VerifiednotBlocknotDelete';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.VerifiednotBlockDelete';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.store';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.show';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.updateName';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.updateCategory';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.updateIcone';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.destroy';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.block';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.unblock';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.indexUnverified';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT' WHERE name = 'Manageequipment.makeVerified';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.assignPermsToRole';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.RevokePermsToRole';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.getUserRoles';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.assignRoleToUser';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.RevokeRoleToUser';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.assignPermsToUser';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.revokePermsToUser';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.getUserPerms';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.usersWithRole';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.usersWithPerm';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.rolesPerms';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.rolesPermsCount';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.usersCountByRole';
UPDATE permissions SET groupe = 'GESTION_ACCES' WHERE name = 'Manageusers.usersRoles';
UPDATE permissions SET groupe = 'GESTION_DES_UTILISATEURS_COTE_ADMINISTRATEUR' WHERE name = 'Manageusers.index';
UPDATE permissions SET groupe = 'GESTION_DES_UTILISATEURS_COTE_ADMINISTRATEUR' WHERE name = 'Manageusers.destroy';
UPDATE permissions SET groupe = 'GESTION_DES_UTILISATEURS_COTE_ADMINISTRATEUR' WHERE name = 'Manageusers.block';
UPDATE permissions SET groupe = 'GESTION_DES_UTILISATEURS_COTE_ADMINISTRATEUR' WHERE name = 'Manageusers.unblock';
UPDATE permissions SET groupe = 'GESTION_DES_UTILISATEURS_COTE_ADMINISTRATEUR' WHERE name = 'Manageusers.getUsersByCountry';
UPDATE permissions SET groupe = 'GESTION_DES_UTILISATEURS_COTE_ADMINISTRATEUR' WHERE name = 'Manageusers.getUsersWithRoletraveler';
UPDATE permissions SET groupe = 'GESTION_DES_UTILISATEURS_COTE_ADMINISTRATEUR' WHERE name = 'Manageusers.getUsersWithRoleHost';
UPDATE permissions SET groupe = 'GESTION_DES_UTILISATEURS_COTE_ADMINISTRATEUR' WHERE name = 'Manageusers.getUsersPartenaire';
UPDATE permissions SET groupe = 'GESTION_DES_UTILISATEURS_COTE_ADMINISTRATEUR' WHERE name = 'Manageusers.getUsersWithRoleAdmin';
UPDATE permissions SET groupe = 'GESTION_PERMISSIONS' WHERE name = 'Managepermission.index';
UPDATE permissions SET groupe = 'GESTION_PERMISSIONS' WHERE name = 'Managepermission.indexbycategorie';
UPDATE permissions SET groupe = 'GESTION_PERMISSIONS' WHERE name = 'Managepermission.store';
UPDATE permissions SET groupe = 'GESTION_PERMISSIONS' WHERE name = 'Managepermission.show';
UPDATE permissions SET groupe = 'GESTION_PERMISSIONS' WHERE name = 'Managepermission.block';
UPDATE permissions SET groupe = 'GESTION_PERMISSIONS' WHERE name = 'Managepermission.unblock';
UPDATE permissions SET groupe = 'GESTION_COMMENTAIRES' WHERE name = 'Managereview.store';
UPDATE permissions SET groupe = 'GESTION_COMMENTAIRES' WHERE name = 'Managereview.show';
UPDATE permissions SET groupe = 'GESTION_COMMENTAIRES' WHERE name = 'Managereview.update';
UPDATE permissions SET groupe = 'GESTION_COMMENTAIRES' WHERE name = 'Managereview.destroy';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.index';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.store';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.show';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.update';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.destroy';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.block';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.unblock';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.active';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.inactive';
UPDATE permissions SET groupe = 'GESTION_DOCUMENT' WHERE name = 'Managedocument.document_inactif';
UPDATE permissions SET groupe = 'GESTION_VERIFICATION_DOCUMENT_HOTE' WHERE name = 'Manageverificationdocumenthote.index';
UPDATE permissions SET groupe = 'GESTION_VERIFICATION_DOCUMENT_HOTE' WHERE name = 'Manageverificationdocumenthote.show';
UPDATE permissions SET groupe = 'GESTION_VERIFICATION_DOCUMENT_HOTE' WHERE name = 'Manageverificationdocumenthote.validateDocuments';
UPDATE permissions SET groupe = 'GESTION_VERIFICATION_DOCUMENT_HOTE' WHERE name = 'Manageverificationdocumenthote.validateDocument';
UPDATE permissions SET groupe = 'GESTION_LANGUES' WHERE name = 'Managelanguage.updateIcone';
UPDATE permissions SET groupe = 'GESTION_LANGUES' WHERE name = 'Managelanguage.destroy';
UPDATE permissions SET groupe = 'GESTION_LANGUES' WHERE name = 'Managelanguage.block';
UPDATE permissions SET groupe = 'GESTION_LANGUES' WHERE name = 'Managelanguage.unblock';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.store';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.indexUnverified';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.storeUnexist';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.show';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.updateName';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.updateIcone';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.destroy';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.makeVerified';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.block';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.unblock';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.VerifiedBlocknotDelete';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.VerifiednotBlocknotDelete';
UPDATE permissions SET groupe = 'GESTION_PREFERENCES' WHERE name = 'Managepreference.VerifiednotBlockDelete';
UPDATE permissions SET groupe = 'GESTION_TYPE_PROPRIETE' WHERE name = 'ManagepropertyType.store';
UPDATE permissions SET groupe = 'GESTION_TYPE_PROPRIETE' WHERE name = 'ManagepropertyType.show';
UPDATE permissions SET groupe = 'GESTION_TYPE_PROPRIETE' WHERE name = 'ManagepropertyType.updateName';
UPDATE permissions SET groupe = 'GESTION_TYPE_PROPRIETE' WHERE name = 'ManagepropertyType.updateIcone';
UPDATE permissions SET groupe = 'GESTION_TYPE_PROPRIETE' WHERE name = 'ManagepropertyType.destroy';
UPDATE permissions SET groupe = 'GESTION_TYPE_PROPRIETE' WHERE name = 'ManagepropertyType.block';
UPDATE permissions SET groupe = 'GESTION_TYPE_PROPRIETE' WHERE name = 'ManagepropertyType.indexBlock';
UPDATE permissions SET groupe = 'GESTION_TYPE_PROPRIETE' WHERE name = 'ManagepropertyType.unblock';
UPDATE permissions SET groupe = 'GESTION_VERIFICATION_DOCUMENT_PARTENAIRE' WHERE name = 'Manageverificationdocumentpartenaire.index';
UPDATE permissions SET groupe = 'GESTION_VERIFICATION_DOCUMENT_PARTENAIRE' WHERE name = 'Manageverificationdocumentpartenaire.show';
UPDATE permissions SET groupe = 'GESTION_VERIFICATION_DOCUMENT_PARTENAIRE' WHERE name = 'Manageverificationdocumentpartenaire.validateDocuments';
UPDATE permissions SET groupe = 'GESTION_VERIFICATION_DOCUMENT_PARTENAIRE' WHERE name = 'Manageverificationdocumentpartenaire.validateDocument';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_HOTE' WHERE name = 'Managelogement.store';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_HOTE' WHERE name = 'Managelogement.updateSensible';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_HOTE' WHERE name = 'Managelogement.updateInsensible';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_HOTE' WHERE name = 'Managelogement.disable';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_HOTE' WHERE name = 'Managelogement.enable';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_HOTE' WHERE name = 'Managelogement.destroyHote';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_HOTE' WHERE name = 'Managelogement.getHousingForHote';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_HOTE' WHERE name = 'Managelogement.HousingHoteInProgress';
UPDATE permissions SET groupe = 'GESTION_COMMISSION_HOTE' WHERE name = 'Managecommissionpartenaire.updateCommissionForSpecifiqueUser';
UPDATE permissions SET groupe = 'GESTION_COMMISSION_HOTE' WHERE name = 'Managecommissionpartenaire.updateCommissionValueByAnother';
UPDATE permissions SET groupe = 'GESTION_REDUCTION_PARTENAIRE' WHERE name = 'Managecommissionpartenaire.updatereductionForSpecifiqueUser';
UPDATE permissions SET groupe = 'GESTION_REDUCTION_PARTENAIRE' WHERE name = 'Managecommissionpartenaire.updatereductionValueByAnother';
UPDATE permissions SET groupe = 'GESTION_nameBRE_RESERVATION_PARTENAIRE' WHERE name = 'Managecommissionpartenaire.updatenumberreservationForSpecifiqueUser';
UPDATE permissions SET groupe = 'GESTION_nameBRE_RESERVATION_PARTENAIRE' WHERE name = 'Managecommissionpartenaire.updatenumberreservationValueByAnother';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT__HOTE_LOGEMENT' WHERE name = 'Managelogement.storeUnexistEquipment';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT__HOTE_LOGEMENT' WHERE name = 'Managelogement.equipementsHousing';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT__HOTE_LOGEMENT' WHERE name = 'Managelogement.deleteEquipement';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT__HOTE_LOGEMENT' WHERE name = 'Managelogement.addEquipment';
UPDATE permissions SET groupe = 'GESTION_PREFERENCE_HOTE_LOGEMENT' WHERE name = 'Managelogement.housingPreference';
UPDATE permissions SET groupe = 'GESTION_PREFERENCE_HOTE_LOGEMENT' WHERE name = 'Managelogement.deletePreference';
UPDATE permissions SET groupe = 'GESTION_PREFERENCE_HOTE_LOGEMENT' WHERE name = 'Managelogement.addPreference';
UPDATE permissions SET groupe = 'GESTION_PREFERENCE_HOTE_LOGEMENT' WHERE name = 'Managelogement.storeUnexistPreference';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES_HOTE_LOGEMENT' WHERE name = 'Managelogement.deletePhotoCategory';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES_HOTE_LOGEMENT' WHERE name = 'Managelogement.addDefaultCategory';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES_HOTE_LOGEMENT' WHERE name = 'Managelogement.addNewCategory';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES_HOTE_LOGEMENT' WHERE name = 'Managelogement.deleteCategory';
UPDATE permissions SET groupe = 'GESTION_CATEGORIES_HOTE_LOGEMENT' WHERE name = 'Managelogement.addPhotoCategory';
UPDATE permissions SET groupe = 'GESTION_PHOTO__HOTE_LOGEMENT' WHERE name = 'Managelogement.updatePhoto';
UPDATE permissions SET groupe = 'GESTION_PHOTO__HOTE_LOGEMENT' WHERE name = 'Managelogement.setCoverPhoto';
UPDATE permissions SET groupe = 'GESTION_PHOTO__HOTE_LOGEMENT' WHERE name = 'Managelogement.deletePhoto';
UPDATE permissions SET groupe = 'GESTION_PHOTO__HOTE_LOGEMENT' WHERE name = 'Managelogement.addPhoto';
UPDATE permissions SET groupe = 'GESTION_CHARGE__HOTE_LOGEMENT' WHERE name = 'Managelogement.addCharge';
UPDATE permissions SET groupe = 'GESTION_CHARGE__HOTE_LOGEMENT' WHERE name = 'Managelogement.listCharge';
UPDATE permissions SET groupe = 'GESTION_CHARGE__HOTE_LOGEMENT' WHERE name = 'Managelogement.deleteCharge';
UPDATE permissions SET groupe = 'GESTION_LOGEMENTS_EN_ATTENTE_DE_VALIDATION_ADMIN' WHERE name = 'Managelogement.indexHousingForValidationForadmin';
UPDATE permissions SET groupe = 'GESTION_LOGEMENTS_EN_ATTENTE_DE_VALIDATION_ADMIN' WHERE name = 'Managelogement.HousingHoteInProgressForAdmin';
UPDATE permissions SET groupe = 'GESTION_LOGEMENTS_EN_ATTENTE_DE_VALIDATION_ADMIN' WHERE name = 'Managelogement.indexHousingForUpdateForadmin';
UPDATE permissions SET groupe = 'GESTION_LOGEMENTS_EN_ATTENTE_DE_VALIDATION_ADMIN' WHERE name = 'Managelogement.showHousingDetailForValidationForadmin';
UPDATE permissions SET groupe = 'GESTION_LOGEMENTS_EN_ATTENTE_DE_VALIDATION_ADMIN' WHERE name = 'Managelogement.ValidateOneHousing';
UPDATE permissions SET groupe = 'GESTION_LOGEMENTS_EN_ATTENTE_DE_VALIDATION_ADMIN' WHERE name = 'Managelogement.ValidateManyHousing';
UPDATE permissions SET groupe = 'GESTION_LOGEMENTS_EN_ATTENTE_DE_VALIDATION_ADMIN' WHERE name = 'Managelogement.UpdateOneHousing';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_ADMIN' WHERE name = 'Managelogement.ListeDesLogementsValideBloque';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_ADMIN' WHERE name = 'Managelogement.ListeDesLogementsValideDelete';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_ADMIN' WHERE name = 'Managelogement.ListeDesLogementsValideDisable';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_ADMIN' WHERE name = 'Managelogement.hote_with_many_housing';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_ADMIN' WHERE name = 'Managelogement.country_with_many_housing';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_ADMIN' WHERE name = 'Managelogement.getHousingDestroyedByHote';
UPDATE permissions SET groupe = 'GESTION_LOGEMENT_ADMIN' WHERE name = 'Managelogement.getTop10HousingByAverageNotes';
UPDATE permissions SET groupe = 'GESTION_CATEGORIE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.validateDefaultCategoryHousing';
UPDATE permissions SET groupe = 'GESTION_CATEGORIE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.getCategoryDefaultInvalidHousings';
UPDATE permissions SET groupe = 'GESTION_CATEGORIE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.getCategoryUnexistInvalidHousings';
UPDATE permissions SET groupe = 'GESTION_CATEGORIE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.validateUnexistCategoryHousing';
UPDATE permissions SET groupe = 'GESTION_CATEGORIE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.getCategoryDetail';
UPDATE permissions SET groupe = 'GESTION_CATEGORIE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.getUnverifiedHousingCategoryFilesWithDetails';
UPDATE permissions SET groupe = 'GESTION_CATEGORIE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.validateHousingCategoryFile';
UPDATE permissions SET groupe = 'GESTION_PHOTO_ADMIN_LOGEMENT' WHERE name = 'Managelogement.getUnverifiedPhotos';
UPDATE permissions SET groupe = 'GESTION_PHOTO_ADMIN_LOGEMENT' WHERE name = 'Managelogement.validatePhoto';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT_ADMIN_LOGEMENT' WHERE name = 'Managelogement.ListHousingEquipmentInvalid';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT_ADMIN_LOGEMENT' WHERE name = 'Managelogement.makeVerifiedHousingEquipment';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT_ADMIN_LOGEMENT' WHERE name = 'Managelogement.ListEquipmentForHousingInvalid';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT_ADMIN_LOGEMENT' WHERE name = 'Managelogement.getHousingEquipmentInvalid';
UPDATE permissions SET groupe = 'GESTION_EQUIPEMENT_ADMIN_LOGEMENT' WHERE name = 'Managelogement.getUnexistEquipmentInvalidForHousing';
UPDATE permissions SET groupe = 'GESTION_PREFERENCE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.getHousingPreferenceInvalid';
UPDATE permissions SET groupe = 'GESTION_PREFERENCE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.getUnexistPreferenceInvalidForHousing';
UPDATE permissions SET groupe = 'GESTION_PREFERENCE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.ListHousingPreferenceInvalid';
UPDATE permissions SET groupe = 'GESTION_PREFERENCE_ADMIN_LOGEMENT' WHERE name = 'Managelogement.makeVerifiedHousingPreference';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_COMMENTAIRES' WHERE name = 'Managereservation.reviews.note.add';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_COMMENTAIRES' WHERE name = 'Managereservation.statistiques_notes.get';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_HOTE' WHERE name = 'Managereservation.hote_confirm_reservation';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_HOTE' WHERE name = 'Managereservation.hote_reject_reservation';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_HOTE' WHERE name = 'Managereservation.showDetailOfReservationForHote';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_HOTE' WHERE name = 'Managereservation.getReservationsByHousingId';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_HOTE' WHERE name = 'Managereservation.reservationsConfirmedByHost';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_HOTE' WHERE name = 'Managereservation.reservationsRejectedByHost';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_HOTE' WHERE name = 'Managereservation.reservationsCanceledByTravelerForHost';
UPDATE permissions SET groupe = 'GESTION_RESERVATIONS_HOTE' WHERE name = 'Managereservation.reservationsNotConfirmedYetByHost';
UPDATE permissions SET groupe = 'GESTION_RESERVATION_ADMIN' WHERE name = 'Managereservation.housing_with_many_reservation';
UPDATE permissions SET groupe = 'GESTION_RESERVATION_ADMIN' WHERE name = 'Managereservation.getAllReservationCanceledByTravelerForAdmin';
UPDATE permissions SET groupe = 'GESTION_RESERVATION_ADMIN' WHERE name = 'Managereservation.getAllReservationRejectedForAdmin';
UPDATE permissions SET groupe = 'GESTION_RESERVATION_ADMIN' WHERE name = 'Managereservation.getAllReservationConfirmedForAdmin';
UPDATE permissions SET groupe = 'GESTION_TRANSACTION' WHERE name = 'Manageportefeuille.transaction.all';
UPDATE permissions SET groupe = 'GESTION_TRANSACTION' WHERE name = 'Manageportefeuille.transaction.history';
UPDATE permissions SET groupe = 'GESTION_TYPE_DE_DEMANDE' WHERE name = 'ManagemethodPayement.store';
UPDATE permissions SET groupe = 'GESTION_TYPE_DE_DEMANDE' WHERE name = 'ManagemethodPayement.index';
UPDATE permissions SET groupe = 'GESTION_TYPE_DE_DEMANDE' WHERE name = 'ManagemethodPayement.show';
UPDATE permissions SET groupe = 'GESTION_TYPE_DE_DEMANDE' WHERE name = 'ManagemethodPayement.updateName';
UPDATE permissions SET groupe = 'GESTION_METHODE_PAIEMENT' WHERE name = 'ManagemethodPayement.updateIcone';
UPDATE permissions SET groupe = 'GESTION_TYPE_DE_DEMANDE' WHERE name = 'ManagemethodPayement.destroy';
UPDATE permissions SET groupe = 'GESTION_METHODE_PAIEMENT' WHERE name = 'ManagemethodPayement.block';
UPDATE permissions SET groupe = 'GESTION_METHODE_PAIEMENT' WHERE name = 'ManagemethodPayement.unblock';
UPDATE permissions SET groupe = 'GESTION_RETRAIT_ADMIN' WHERE name = 'Manageretrait.ListRetraitWaitingConfirmationByAdmin';
UPDATE permissions SET groupe = 'GESTION_RETRAIT_ADMIN' WHERE name = 'Manageretrait.ListRetraitOfTravelerWaitingConfirmationByAdmin';
UPDATE permissions SET groupe = 'GESTION_RETRAIT_ADMIN' WHERE name = 'Manageretrait.ListRetraitOfHoteWaitingConfirmationByAdmin';
UPDATE permissions SET groupe = 'GESTION_RETRAIT_ADMIN' WHERE name = 'Manageretrait.ListRetraitConfirmedByAdmin';
UPDATE permissions SET groupe = 'GESTION_RETRAIT_ADMIN' WHERE name = 'Manageretrait.validateRetraitByAdmin';
UPDATE permissions SET groupe = 'GESTION_RETRAIT_ADMIN' WHERE name = 'Manageretrait.ListRetraitRejectForAdmin';
UPDATE permissions SET groupe = 'GESTION_RETRAIT_ADMIN' WHERE name = 'Manageretrait.rejectRetraitByAdmin';
UPDATE permissions SET groupe = 'GESTION_CHARGE_ADMIN' WHERE name = 'Managecharge.index';
UPDATE permissions SET groupe = 'GESTION_CHARGE_ADMIN' WHERE name = 'Managecharge.store';
UPDATE permissions SET groupe = 'GESTION_CHARGE_ADMIN' WHERE name = 'Managecharge.updateName';
UPDATE permissions SET groupe = 'GESTION_CHARGE_ADMIN' WHERE name = 'Managecharge.updateIcone';
UPDATE permissions SET groupe = 'GESTION_CHARGE_ADMIN' WHERE name = 'Managecharge.destroy';

        ";

        DB::unprepared($sql);
    }

    public function down()
    {

        Schema::table('permissions', function (Blueprint $table) {
            $table->dropColumn('groupe');
        });
    }
}

